[project]
name = "ceph-mgr-microceph"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "ceph",
    "requests>=2.32.3",
    "snap-helpers",
    "urllib3>=2.4.0",
]

[tool.uv.sources]
ceph = { git = "https://github.com/ceph/ceph", subdirectory = "src/python-common", rev = "squid" }
snap-helpers = { git = "https://github.com/albertodonato/snap-helpers" }
